### ISSUE TITLE
Problematic templating issue in code blocks

### ISSUE THREAD

**Issue by sgibson91** [carpentries/lesson-example#343]
<details>
<summary><strong>Instructions</strong></summary>

Thanks for contributing! :heart:

If this contribution is for instructor training, please email the link to this contribution to
checkout@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!

If this issue is about a specific episode within a lesson, please provide its link or filename.

Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries Team at team@carpentries.org.

You may delete these instructions from your comment.

\- The Carpentries
</details>

Hi folks! 👋🏻 

Thanks for this lesson template - it is really cool!

I'm currently writing a lesson that contains a GitHub Actions example as a code block using YAML syntax-highlighting. In this example, the `GITHUB_TOKEN` is called via the syntax `${{ secrets.GITHUB_TOKEN }}` and Jekyll is having trouble rendering this line, I'm assuming because of the `{{ }}`'s meaning as a template function. Please see the images below.

| <img width="563" alt="Screenshot 2021-05-17 at 14 50 21" src="https://user-images.githubusercontent.com/44771837/118499957-4b4ae200-b71f-11eb-92b7-c5c722cc6377.png"> | <img width="670" alt="Screenshot 2021-05-17 at 14 50 06" src="https://user-images.githubusercontent.com/44771837/118500000-543bb380-b71f-11eb-8264-b298e86a4b47.png"> |
| :---: | :---: |
| Source file | Rendered by Jekyll |

I've managed to work-around this problem with the below:

| <img width="547" alt="Screenshot 2021-05-17 at 15 12 02" src="https://user-images.githubusercontent.com/44771837/118503676-c06be680-b722-11eb-829a-a09e0247a6c5.png"> | <img width="605" alt="Screenshot 2021-05-17 at 15 12 13" src="https://user-images.githubusercontent.com/44771837/118503695-c4980400-b722-11eb-8914-30a3140f36d1.png"> |
| :---: | :---: |
| Source file | Rendered by Jekyll |

But this does produce a warning from Liquid:

<img width="672" alt="Screenshot 2021-05-17 at 15 12 30" src="https://user-images.githubusercontent.com/44771837/118503796-dc6f8800-b722-11eb-8f1a-291573fd16de.png">

I'm not familiar with Liquid, so I'm struggling to understand if I've made a Liquid faux-pas here. I wondered if there is a more elegant way to handle this, or if it could be possible to update the code block boilerplate in such a way that curly braces aren't automatically templated as they would be elsewhere (or make it optional)?

My repository is here: https://github.com/sgibson91/blogging-with-hugo-and-github-pages

Thanks in advance!

**Comment by tobyhodges** [comment]
Hey @sgibson91! Thanks for asking this question and for using the lesson template. The intended way to handle such cases with Liquid is to use [`raw` tags](https://shopify.github.io/liquid/tags/template/), e.g.

```YAML
~~~
{% raw %}name: Build and Deploy Site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build site with Hugo
        run: hugo --minify

      - name: Check HTML
        uses: chabad360/htmlproofer@master
        with:
          directory: "./public"
          arguments: --only-4xx --check-favicon --check-html --assume-extension --empty-alt-ignore --disable-external
        continue-on-error: true

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{"{{"}} secrets.GITHUB_TOKEN {{}}}}
          publish_dir: ./public{% endraw %}
~~~
{: .language-yaml }
```

This is a solution we have had to employ many times while writing a lesson in Jekyll about using Jekyll, so you can find [many more examples of `raw` tag usage](https://github.com/carpentries-incubator/jekyll-pages-novice/blob/gh-pages/_episodes/includes.md) in the relevant lesson repository: https://github.com/carpentries-incubator/jekyll-pages-novice/
